WIP: feature add sharding selector
ecodeclub/eorm pull request #145
Opened 2023-02-04 14:41 UTC by Stone-afk

这是初步草稿思路： 
- Get那里确保只能生成一个 SQL，我理解是直接简单初爆的做判断？；
- 还有个人觉得表和库的sharding方法应该分开；

2023-02-04 15:31 UTC, flycash commented
sharding 内部使用的放进去 internal 里面，如果是暴露给用户的接口，那么可以直接放在顶级目录下面，也可以在顶级目录下面创建一个 sharding 包；

分开其实也可以，只不过分开之后的设计可能会很像，因为理论上来说，任何可以被用来分库的算法，也可以用来分表。这个你随意，我不介意；

Get 那里你先直接粗暴判断，后面我们再来重构

2023-02-07 04:18 UTC, flycash requested changes
思路是没什么问题的，你继续把 Build 写下去，然后补充单元测试。单元测试先试试 Build 方法就行。

2023-02-07 04:18 UTC, flycash commented on sharding_select.go
> +	case opGT:
除了 EQ，其它都让它跑到 default 里面。

2023-02-07 04:18 UTC, flycash commented on sharding_select.go
> +			return nil, errors.New("too complex query, temporarily not supported")
用中文吧，反正也没打算给老外用。老外想用就自己翻译一下中文

2023-02-07 04:18 UTC, flycash commented on sharding_select.go
> +		right, isVals := pre.right.(values)
这边应该是断言是 value，values 我没记错的话是给 IN 用的？

2023-02-07 04:18 UTC, flycash commented on sharding_select.go
> +		DBSf := s.meta.DBShardingFunc
小写

2023-02-12 08:50 UTC, flycash commented
> sharding selector 与 selector 存在大量的重复方法，这个是否需要共同的实现一个接口，以及 添加一个基础的抽象 如 BaseSelector, 不过泛型的话这里会很丑

可以将一部分数据结构下沉到 internal 里面，而后 ShardingSelector 和普通的 Selector 共同依赖于这部分

2023-02-17 05:52 UTC, flycash requested changes
全部注释什么的用中文。之前我用英文是因为那时候脑子进水了

2023-02-17 05:52 UTC, flycash commented on sharding_db.go
> +	DBs map[string]*DB
这个改用新合并进去的 MasterSlavesDB

2023-02-17 05:52 UTC, flycash commented on sharding_select.go
> +func (s *ShardingSelector[T]) RegisterTableMeta(meta *model.TableMeta) *ShardingSelector[T] {
不要使用这个方法。你可以认为，用户需要主动注册元数据:
```go
r.Register(enity, shardingRule)
```
也就是用户在使用之前必须要主动的注册分库分表的规则。那么你可以认为你在 ShardingSelector 里面拿到的就是有分库分表规则的 TableMeta

2023-02-17 05:52 UTC, flycash commented on sharding_select.go
> +	}
这些我觉得其实没太大必要去检测。应该说默认是对的，只有在找不到的时候再报错。比如说你在使用 shardingKey 的时候发现有问题了，然后你再报错。不需要提前检测。就是不需要当保姆

2023-02-17 05:52 UTC, flycash commented on sharding_select.go
> +		s.builder.core = sess.getCore()
这一部分不需要。core 你在 NewSelector 的时候就要决定。这种情况下，我们不要允许用户在分库分表里面使用不同的 core

2023-02-17 05:52 UTC, flycash commented on sharding_select.go
> +func (s *ShardingSelector[T]) buildQuery(db, tbl string) (*ShardingQuery, error) {
抽象出来一个 selectorBuilder，然后 Selector 和 ShardingSelector 都组合了 selectorBuilder，并且 selectorBuilder 也组合了 builder

2023-02-17 05:52 UTC, flycash commented on sharding_select.go
> +	case opAnd, opOr:
你这边搞错了。对于 AND 来说：
- 如果左边没有，那么就用右边的；反之亦然
对于 OR 来说：
- 如果左边没有，那么就用广播
大概是这样，我记得我们在课程上讨论了很久这个问题

2023-02-17 05:52 UTC, flycash commented on sharding_select_test.go
> +	for _, tc := range testCases {
你需要 OR 的测试用例。

同时你还要增加 AND 和 AND，AND 和 OR，OR 和 OR 这种多层次的测试用例

2023-02-17 05:52 UTC, flycash commented on sharding_select_test.go
> +	testCases := []struct {
如果你单独测试了这个方法，那么前面的 Build 测试用例就可以简单一点。比如说把复杂的 AND OR 之类的测试挪下来这里

2023-02-17 06:55 UTC, Stone-afk commented on sharding_select.go
> +func (s *ShardingSelector[T]) RegisterTableMeta(meta *model.TableMeta) *ShardingSelector[T] {
这个方法的逻辑其实是使用这个，register 好的 meta

2023-02-17 07:03 UTC, Stone-afk commented on sharding_db.go
> +	DBs map[string]*DB
这里是不是让用户决策使用什么类型的 DB 会好一点

2023-02-17 07:05 UTC, Stone-afk commented on sharding_select.go
> +		s.builder.core = sess.getCore()
也就是说， 不允许不同 方言的 DB 支持？这里这样写是为了考虑到不同 DB 的 driver 类型可能不同

2023-02-18 02:58 UTC, Stone-afk commented on sharding_select.go
> +		s.builder.core = sess.getCore()
metaRegistry 也是存在在每一个 db 里的

2023-02-25 13:32 UTC, flycash approved these changes
我先合并了，它还很多 BUG，但是这算是我的 锅，我应该拆分得更加细一点。不过说实在的，我也很难拆了=。=

2023-02-25 13:32 UTC, flycash commented on sharding_db.go
> +		return "", errs.ErrCtxGetDBName
ErrDBNotSpecified

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +		s.args = make([]any, 0, 8)
看起来有点奇怪，因为对应的 buffer 也是需要重置的

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +		s.args = make([]any, 0, 8)
把它和 buffer 重置放一起，然后定义一个新的方法 reset()

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +	s.end()
之前我说过引入一个 selectorBuilder。然后把 Selector 和 ShardingSelector 共用的东西丢进去

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +		return s.mergeOR(left, right), nil
我觉得这种，说不定有办法合并在一起，或者说用一个公共的方法，然后传入 len(left) == 0 之类返回啥的，看上去有一点点可能。不然两个方法太像了，你可以试试？我不是很确定

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +		}
在这里 mark 一个 TODO，过于严苛的校验。因为我觉得将来我们可能要考虑类似于 sk = 123 AND a = now() 这种。那么很显然右边这个 a=now() 的列 a 并不是我们的分库分表键，那么我们可以考虑说返回全集

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +		}
也就是说，如果 left op right 这种形态下， left 是列并且是分库分表键，那么再考虑看右边的值。如果左边的 left 不是列，或者不是分库分表列，那么就直接返回全集。因为它没有命中任何的分库或者分表，所以走全集

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +			}
这边 wrap 一下这个原始 err，不然丢到了原始的 err 信息。

2023-02-25 13:32 UTC, flycash commented on sharding_select.go
> +			}
我记得 1.20 支持 wrap 多个 error 了，你直接升级上去 1.20，记得修改 go mod 和 github action 的版本

2023-02-25 13:32 UTC, flycash commented on sharding_db.go
> +func ShardingDBOptionWithTables(m map[string]bool) ShardingDBOption {
暂时不要暴露出去。理论上来说这个东西，应该是从分库分表规则里面推断出来的。所以其实我倾向于让分库分表的抽象来负责计算所有的候选 DB 和候选表

2023-02-25 13:32 UTC, flycash commented on sharding_db.go
> +func (s *ShardingDB) broadcast() []Dst {
所以在广播的时候你会出现问题，就是比如说我这个数据库虽然分库分表了，但是我其实 Order 表和 OrderDetail 表都在这个库上，那么你这里的广播就会导致，原本我只查询 Order 表的，结果你会广播过去 OrderDetail。这也就是我说，应该定义在分库分表规则上的

2023-02-25 13:32 UTC, flycash commented on sharding_select_test.go
> +			builder: func() ShardingQueryBuilder {
你这个不是已经传入了 UserId 吗？

2023-02-25 13:32 UTC, flycash commented on sharding_select_test.go
> +				s := NewShardingSelector[Order](shardingDB).Where(C("UserId").EQ(int64(123)))
这个 Selector 和前面一个测试用例不是一样的吗？

2023-02-25 13:32 UTC, flycash commented on sharding_select_test.go
> +		},
这几个不是测试 WHERE 部分写法的，挪出去单独作为一个测试，因为它们不太重要=。=后面等我支持聚合函数的时候再考虑弄回来

2023-02-25 13:32 UTC, flycash commented on sharding_select_test.go
> +					Where(C("OrderId").EQ(int64(12)).And(C("UserId").EQ(int64(123))))
我在 opEQ 那里评价太苛刻就是类似这种用法，例如 C("OrderId").Eq(Raw("now()"))

2023-02-25 13:33 UTC, flycash approved these changes

2023-02-25 13:34 UTC, merged