WIP：feature 增强的 ShardingAlgorithm 设计与实现
ecodeclub/eorm pull request #162
Opened 2023-03-01 04:41 UTC by Stone-afk

2023-03-02 07:40 UTC, flycash commented
@Stone-afk 记得合并代码，可能有冲突

2023-03-06 03:36 UTC, flycash commented on internal/sharding/hash.go
> -	panic("implement me")
这个创建一个新的子目录，丢进去。然后这个实现先不用琢磨，后面再来考虑。有一个凑合能用的来支持测试就可以了

2023-03-10 02:49 UTC, flycash requested changes

2023-03-10 02:49 UTC, flycash commented on internal/sharding/hash/hash.go
> +type Hash struct {
哈希和shadow hash 标注一个experiemntal，就是实验特性，这个地方将来还得再来重构，也就是那么两三周之后

2023-03-10 02:49 UTC, flycash commented on internal/sharding/hash/hash.go
> +type Hash struct {
后面我再单独创建 issue 来审视着两个实现

2023-03-10 02:49 UTC, flycash commented on master_slave_db.go
> +func OpenClusterDB(ms map[string]*MasterSlavesDB) *ClusterDB {
其实倒是觉得暴露了 Set 方法就不需要传入一个 ms 了=。=或者加一个注释，不允许传入 nil。

2023-03-10 02:49 UTC, flycash commented on master_slave_db.go
> +}
后面我要考虑把 Datasource 组合一下 Session。比如说如果我们认为 Session 是一个执行器，那么 Datasource 本身也是一个执行器。

唯独比较恶心的是，我们在各个 Builder 里面需要 core 这个东西。

2023-03-10 02:49 UTC, flycash commented on sharding_db.go
> +	sharding.DataSource
你有 ClusterDB 之后这个就可以删了吧？

2023-03-10 02:49 UTC, flycash commented on sharding_select.go
> +			if r.Name != l.Name || r.DB != l.DB || r.Table != l.Table {
把这个判断重构为一个方法，放在 r 上

2023-03-10 02:49 UTC, flycash commented on sharding_select.go
> +			if r.Name == l.Name && r.DB == l.DB && r.Table == l.Table {
这个也可以定义为一个方法，放在 r 上。它和后面的 OR 应该是一个取反的关系，所以可以只定义一个，也可以两个都定义

2023-03-10 02:49 UTC, flycash commented on sharding_select.go
> -	if len(qs) == 0 {
这个去掉之后你是觉得肯定不会 0 个查询了吗？

2023-03-10 02:49 UTC, flycash commented on internal/sharding/hash/hash.go
> +	DBPattern    *sharding.Pattern
Pattern 不能定义为 sharding 包的，因为它属于具体实现的概念。你可以想象，有一些实现压根就不会有 Pattern 这种说法

2023-03-10 02:49 UTC, flycash commented on internal/sharding/hash/hash.go
> +		DBName := fmt.Sprintf(h.DBPattern.Name, i)
局部变量首字母都要小写……保持这个习惯……

2023-03-10 03:46 UTC, Stone-afk commented on sharding_db.go
> +	sharding.DataSource
并不是， cluster db 实现了 datasource， sharding db 可以通过 cluster name 来找到 cluster 实例， 通过 cluster 实例来找到具体的master slave

2023-03-10 03:49 UTC, Stone-afk commented on master_slave_db.go
> +}
还需要一个具体的cluster 实现，应为 master slave 不代表 cluster， sql.DB 的数据库连接是包含 库名称的， 但是集群不应该包含具体的db名称

2023-03-10 03:50 UTC, Stone-afk commented on master_slave_db.go
> +func OpenClusterDB(ms map[string]*MasterSlavesDB) *ClusterDB {
这个 cluster db 还没想好怎么写，这里暂时的

2023-03-10 03:53 UTC, Stone-afk commented on internal/sharding/hash/hash.go
> +	DBPattern    *sharding.Pattern
这个要放什么地方呢，因为非sharding 目录用不到 该实现，除非再建一个 工具目录

2023-03-10 12:54 UTC, flycash commented on internal/sharding/hash/hash.go
> +	DBPattern    *sharding.Pattern
就放在 Hash 这里

2023-03-11 07:58 UTC, flycash requested changes
Hash 和 shadow_hash 不着急，我们后面支持了范围查询之后再一起重构这两个。我是倾向于把它们整个挪出去的

2023-03-11 07:58 UTC, flycash commented on sharding_db.go
> +func ShardingDBWithDataSource(ds sharding.DataSource) ShardingDBOption {
这个是不是应该初始化的时候一定要传进来？而不是作为一个可选的。因为我也没看到你有提供默认的 Datasource

2023-03-11 07:58 UTC, flycash commented on sharding_select.go
> +func (*ShardingSelector[T]) mergeOR(left, right sharding.Result) sharding.Result {
这两个方法能不能用 ekit 里面取并集和交集的方法替换掉，我记得我在 ekit/slice 里面定义过并集和交集的方法

2023-03-11 07:58 UTC, flycash commented on sharding_select.go
> +func (*ShardingSelector[T]) mergeOR(left, right sharding.Result) sharding.Result {
先试试，不好搞就算了，因为我也不确定我设计的并集和交集的方法好不好用

2023-03-11 15:44 UTC, Stone-afk commented on sharding_db.go
> +func ShardingDBWithDataSource(ds sharding.DataSource) ShardingDBOption {
默认的 Datasource 是 sharding Datasource

2023-03-11 15:45 UTC, Stone-afk commented on sharding_db.go
> +func ShardingDBWithDataSource(ds sharding.DataSource) ShardingDBOption {
这里做不成可选的吧

2023-03-12 05:33 UTC, flycash requested changes
你看看为什么代码覆盖率那么低。

2023-03-12 05:33 UTC, flycash commented on sharding_db.go
> +func ShardingDBWithDataSource(ds sharding.DataSource) ShardingDBOption {
我是说实现。你在 OpenShardingDB 里面不是没有任何初始化吗？

2023-03-12 05:33 UTC, flycash commented on sharding_select.go
>  	defer bytebufferpool.Put(s.buffer)
在这里就不要放回去了，重置整个 buffer。然后在调用方 Build 那里全部构建完，然后再放回去

2023-03-12 05:33 UTC, flycash commented on sharding_select.go
> +			return sharding.EmptyResult, errs.ErrUnsupportedTooComplexQuery
这个要加一个测试覆盖了

2023-03-12 05:33 UTC, flycash commented on internal/sharding/types.go
> +func (r Dst) IsIntersection(l Dst) bool {
应该叫做 Equals。就是两个是否相等。因为 Union 之类的概念，是你上层处理操作符引入的概念，本身 Dst 是没有这个概念的。它只有我判断两个 Dst 是否相等的概念。那么我们在上层的时候，取并集就是要求两个一定要相等。

2023-03-12 05:34 UTC, flycash commented
有几个文件被你修改之后，测试覆盖率下降得厉害，你看看

2023-03-12 15:25 UTC, Stone-afk commented on sharding_select.go
>  	defer bytebufferpool.Put(s.buffer)
OpenShardingDB 初始化 core 的内容

2023-03-12 16:21 UTC, Stone-afk commented on sharding_db.go
> +func ShardingDBWithDataSource(ds sharding.DataSource) ShardingDBOption {
OpenShardingDB 初始化 core 的内容

2023-03-13 14:10 UTC, flycash approved these changes

2023-03-13 14:11 UTC, merged