分库分表：merger 排序实现
ecodeclub/eorm pull request #166
Opened 2023-03-04 04:11 UTC by juniaoshaonian

scan方法我没有实现

2023-03-04 12:43 UTC, flycash commented
这个思路是没问题，不过有几个点：
- 所有的 merger 不能依赖于 ORM 的任何其它包，因为将来我就要拆出去的，给别的分库分表用的；
- 要采用延迟读数据的策略。你可以预期用户传入的 `results []*sql.Rows` 中的每一个元素的数据，都是拍好序了的，所以对你来说，你就是一个延迟归并的过程。比如说 A B C 三个，当用户第一次调用 Next，你需要取出来 A B C 的第一条数据，然后找到最小的那个，把指针指向这个最小的，假如说是 A 的，那么 B C 的你就要临时存起来。等调用 Scan ，那么你就是用刚才 A 中的数据去填充，这里面也就是我说的类型转换很麻烦，因为之前你在 A 读出来的时候，可以考虑用 []byte 去接收，然后在 Scan 的时候就要转过去用户需要的数据类型；

数据类型的转换，在 sql 包里面是 convertAssignRows 这个东西。所以基本上就是抄一遍这个方法。实在无力吐槽这个关键的方法它居然是私有的。

这里面是有隐患的，就是你在 Next 的时候就需要取出来数据，然后临时存着。理论上来说用 []byte 不会有什么问题，但是我觉得这里面可能有不少的坑。

2023-03-04 12:44 UTC, flycash commented
你考虑这样一个场景，就是分页的场景，比如说排序之后取（LIMIT 100,10），那么你完全不需要全部排序一遍，而是就只排序一部分。

2023-03-04 12:47 UTC, flycash commented
那么 Scan 里面，就调用你抄过来的那个 ConvertAndAssign 就可以。

2023-03-04 16:28 UTC, longyue0521 requested changes

2023-03-04 16:28 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +	}
1. 把这段代码以函数的形式抽出来给它一个描述性名称,比如initHeap
2. 把构造Rows的过程抽出来,最好达到`return newRows(xxxx), nil`的效果
3. 还可以试试在Rows[T].Next()方法中利用once.Do调用这个方法来实现真正的延迟调用,缺点是第一次调用Next的时间可能有些长

2023-03-05 02:22 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
学到了

2023-03-06 02:56 UTC, flycash requested changes

2023-03-06 02:56 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +type Merger[T any] struct {
这个 Merger 肯定不可能是泛型的。注意，在 merger 这个包，它完全没有任何将数据转化为结构体的概念。

2023-03-07 02:51 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
大佬这样写go linter会报错

2023-03-07 02:53 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
@longyue0521 大佬知道是为啥不

2023-03-07 05:17 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
1. 半截信息看不出个所以然
2. 把你重构后的代码、命令行执行命令的过程及结果完整地贴出来
3. 你用的go版本、golangci-lint的版本

2023-03-07 05:20 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
@juniaoshaonian  参考思路不是照搬照抄 `func(any, any, bool)` -> `func(any, any, Order)`

2023-03-07 05:27 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
如果还报错

1. 把你重构的代码、命令行界面（包含完整执行命令的过程及结果）全部贴出来
2. 以及go的版本，golangci-lint的版本

2023-03-07 06:51 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
https://www.yuque.com/alipaywopdxn0wdh/nunbo2/mgw3c1pvepmb6gkd?singleDoc# 《无标题》
@longyue0521 大佬可以瞅瞅

2023-03-07 07:17 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
1. 把你重构后的**整个merger.go及merger_test.go文件**贴一下
2. 输出我想看到命令行全部截图，包含从你执行的命令开始，比如`$ golangci-lint run` 或者 `$make lint`开始到最后的截图，不要截断！！！

你现在传的截图都是截断后的，比如 
![image](https://user-images.githubusercontent.com/6337745/223350839-41792ca4-f041-46f6-aa0b-17325911c9e3.png)
最后那个行 in t 往后的内容呢？

2023-03-07 07:22 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
另外，你重构后你运行一下merger_test.go看是否能通过，如果都能通过证明go1.19是支持这么写的，我的版本1.20.1；那么剩下来的问题就是golangci-lint 的问题

2023-03-07 07:25 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
我的测试什么都能通过，我想应该是golangci -lin的问题

2023-03-07 07:26 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
那个完整代码我全贴上去了

2023-03-07 07:49 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
1. 直接运行`golangci-lint run` 是否会出现同样错误？
2. 用script/setup.sh重新安装一下golangci-lint 再试试
3. 安装最新版本golangci-lint是否会出现同样错误

2023-03-07 08:27 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
大佬换成golangci-lint最新版本ok了，谢谢啦^_^

2023-03-07 08:53 UTC, juniaoshaonian commented
迭代过程中的错误处理我是这样搞的，无论是排序过程中遇到的，还是sql.rows的Next方法遇到的错误。都会结束迭代，调用close方法然后返回false。

2023-03-07 12:43 UTC, longyue0521 requested changes

2023-03-07 12:43 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +			}
这段代码中n.index = i可以去掉,剩下的代码与下方代码段重复

2023-03-07 12:43 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +	}
与上方代码段重复,抽取方法去重

2023-03-07 12:43 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				ms.mock01.ExpectQuery("SELECT *").WillReturnRows(sqlmock.NewRows([]string{"id", "name", "address"}).AddRow(1, "abex", "cn").AddRow(2, "bruce", "cn").AddRow(2, "zwl", "cn"))
消除 []string{"id", "name", "address"} 重复, 检查所有类似情况去重

2023-03-07 12:43 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				row01, _ := ms.mockDB01.QueryContext(context.Background(), "SELECT * FROM `t1`;")
"SELECT * FROM `t1`;" 同上, 去重

2023-03-07 12:43 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +		sortMap:    sortMap,
因sortmap的作用就是为了通过name->index->SortColumn最终找到排序列, 将两者封装为一个实体/模型/抽象

```go
type SortColumns []SortColumn
// 或者
type SortColumns struct {
    columns []SortColumn
    mapping map[string]int
}
// 预计排序列不会很多,直接用顺序查找也可以
func (s SortColumns) Has(name string) bool
func (s SortColumns) Find(name string) SortColumn
func (s SortColumns) Get(index int) SortColumn
func (s SortColumns) Len() int
```

2023-03-07 12:45 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func Compare(vali, valj any, order Order, sortColumnType reflect.Kind) int {
OK, 每次解决完的问题/结束的对话,你那边点击一下“resolve”按钮

2023-03-08 03:19 UTC, longyue0521 requested changes

2023-03-08 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestNewMerger() {
TestMerger_New

2023-03-08 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestClose() {
TestRows_Close

整理相关测试的顺序使其更易阅读 比如 TestMerger_New, TestMerger_Merge -> TestRows_NextAndScan TestRows_Close

2023-03-08 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestMerger_NextAndScan() {
拆解为 TestMerger_Merge() 和 TestRows_NextAndScan() 两个测试用例

2023-03-08 05:06 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	colName, ok := m.checkSortColumns(cols, m.sortColumns.columns)
inline是啥？

2023-03-08 09:14 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +	colName, ok := m.checkSortColumns(cols, m.sortColumns.columns)
go:inline 的标记？

2023-03-08 09:30 UTC, flycash requested changes

2023-03-08 09:30 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +		return errs.NewInvalidSortColumn(colName)
这个地方是不是指返回的列里面没有我们需要的排序列？如果是的话，错误信息精确描述一下。我觉得这会是一个比较容易引起不知道分库分表细节的开发者的误解

2023-03-08 09:30 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +	for i := 0; i < len(dest); i++ {
是不是要加锁？感觉就是万一用户并发 next 和 scan，这边会寄了

2023-03-08 09:30 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +	r.once.Do(func() {
这边我有点不确定，我们是挪过去 Rows 创建那里，还是放在这里。

2023-03-08 09:30 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +		err = row.Close()
使用 multierr 把它们拼起来

2023-03-08 09:32 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +	colName, ok := m.checkSortColumns(cols, m.sortColumns.columns)
重构策略 extract method的反向操作inline method，就是将checkSortColumns方法内的语句在其调用点处展开，然后删掉checkSortColumns方法。

2023-03-08 09:50 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	r.once.Do(func() {
我觉得可以放在这，之前龙跃老哥说的，放在这里比较符合语义，我们和sql.rows的Next方法保持一致

2023-03-08 09:51 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +			name: "int  sortColumn ASC,string sortColumn ASC ",
是的。就是 merger 这里用的是真实的列名，因为它没有 ORM 的那种概念

2023-03-08 09:51 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +type Hp struct {
把这个东西拆出去作为一个单独的文件

2023-03-08 09:51 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +	ok := r.nextRows(row, r.cur.index)
这个地方是不是没有办法处理这种场景，比如说我有三个 Rows，其中：
- 1, 2, 3, 4, 5
- 6
- 7, 8, 9, 10

也就是 Rows 返回的行数并不是相同的。那么就会出现一个 Rows 的行被提前取完。那么更加极端的就是，有些 Rows 根本没有，就是查询条件都不符合没有返回任何行数；或者只有其中一个 Rows 是返回了数据的，其它都没有；最极端的就是，全部都没有

2023-03-08 10:12 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	ok := r.nextRows(row, r.cur.index)
应该不会，我后面测了sqlrows为空的情况，那些提前取完的。他就不会再扔到堆里面了。

2023-03-09 03:19 UTC, longyue0521 requested changes

2023-03-09 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			rows, err := merger.Merge(ctx, tc.sqlRows())
require.NotNil(t, rows) 就可以了，当前测试用例的名称是TestMerger_Merge 一般命名策略为： `Test[被测对象]_[被测方法][And被测方法]()`

测试的主要对象是Merger的merge方法

2023-03-09 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			assert.Equal(t, tc.wantSortCols(), r.sortColumns)
这些全去掉，这些与rows相关的测试应该放到TestRows_NextAndScan中，在TestRows_NextAndScan中的测试也会间接验证到你现在写的这些断言，本测试用例只要保证merge返回的rows不为空即可。

另外，不要测试实现，要测试行为/接口。你这里`rows.(*Rows)`就是测试实现，一旦重构时就会导致测试修改，争取做可以在不修改已有测试代码的情况下重构产品代码。

2023-03-09 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestMerger_Merger() {
TestMerger_Merge

2023-03-09 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestMerger_NextAndScan() {
TestRows_NextAndScan

2023-03-09 03:19 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestMerger_Close() {
TestRows_Close()

你在本地修改完后，记得点击resolve按钮

2023-03-09 03:49 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	for i := 0; i < len(dest); i++ {
我加了

2023-03-09 08:11 UTC, flycash approved these changes
@longyue0521 @Stone-afk 麻烦看看。@Stone-afk 你会是主要用户，所以你看看是否符合你的预期

2023-03-09 08:56 UTC, longyue0521 requested changes

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			require.NotNil(t, rows)
改为

```go
rows, err := merger.Merge(ctx, tc.sqlRows())
cancel()
require.NotNil(t, rows)
assert.Equal(t, tc.wantErr, err)
```

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "int  sortColumn ASC,string sortColumn ASC ",
你这个sortColumn到底要表示是什么？，`name`是用来描述测试场景的，好的名字让他人一看就知道你这个测试用例要测试什么，而不需要翻看测试代码实现才能明白你要测试 . 你可以直接写完整的SQL语句，或者只写排序部分`name:"id ASC, address ASC"`

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				return res
重构，提示如下

```go
// 原来的res := make([]*sql.Rows, 0, 3)中3很容易出问题，后续添加一行就会导致扩容
rows := make(....,  0, len(dbs))
for _, db  := range dbs {
    row, err := db.QueryCx......
    require.NoError(t, err)
    rows = append( ...
}
return rows
```

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				return res
重构，同上

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				return res
重构，同上，这里就出现了我上面说的增加row04时，那个3就不准了

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				return res
重构，同上

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +		res = append(res, row03)
重构，同上

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			val := cp(tc.values[0], tc.values[1], tc.order)
cp是copy的常用缩写，cmp是compre常用缩写

2023-03-09 08:56 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +		require.NoError(t, err)
用for循环重构


记得点resolve，全改完了在右上角可以找到review者的头像，点击旁边的+按钮请求review

2023-03-09 10:40 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			require.NotNil(t, rows)
老哥这个这么改不行吧，我需要判断没有错误才会对rows进行判断

2023-03-09 11:30 UTC, longyue0521 requested changes

2023-03-09 11:30 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				return NewMerger(NewSortColumn[int]("id", ASC))
缺少name

2023-03-09 11:30 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "id ASC,name ASC ",
从用户角度思考并重新设计测试用例,思路如下:

1. 排序列集合
    - 列的个数为1, n
    - 列出现的顺序
    - 列升序、降序
2. sqlRow集合中
    - sqlRows包含行数问题
      - 所有sqlRows返回的行数都相同 ——  0, 1, n
      - 所有sqlRows返回的行数都不同 —— 不同的行数 1, n
      - 所有sqlRows返回的行数部分相同 —— 不同/相同的行数为 0, 1, n
    - sqlRows读取数据的顺序问题
        - 先读完1,再读完2...即一个读完才读下一个
        - 1,2,3,4或1,3,4,2 —— 轮训/交叉读取;
        -  读取初期、中期、最后遇到空行
    
精心设计测试用例及数据以找到最小的测试用例集来覆盖上各个维度的组合场景.

2023-03-09 11:30 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +		}
你这么写我才看明白,这个测试用例的目的有些不明确,你描述一下你在TestRows_Close中你想测什么?

2023-03-09 11:32 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				return NewMerger(NewSortColumn[int]("age", ASC), NewSortColumn[int]("id", ASC))
Ok了

2023-03-09 13:35 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +		}
我想测试多次调用都没问题

2023-03-09 13:37 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "id ASC,name ASC ",
大佬你这个看看还缺啥测试用例

2023-03-09 15:04 UTC, longyue0521 requested changes

2023-03-09 15:04 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +		}
之前的对话框怎么没了? 你不要用git puh -f 强推哈,这个会使对话框消失的.

我知道你想多次调用Close看是否等效,但如何判断Close真的生效了呢?是不是得再读一次遇到错?才能证明真的是你Close生效了呢?

```go
for ... i < len(rowsList);... {
    err = rows.Close()
    require.NoError(t, err)
    // 用rowsList[i] 证明确实Close生效了,而不是被读完了自动关闭了
}
```

2023-03-10 03:10 UTC, longyue0521 requested changes

2023-03-10 03:10 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id  ASC,name  ASC_全部sqlrows返回的行数均为空_部分sqlRows返回行数相同_交叉读取各个sqlRows",
全部sqlrows返回的行数均为空_部分sqlRows返回行数相同 ????

2023-03-10 03:10 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("close", func(t *testing.T) {
这里为什么用subtest? 名字还是close ?

2023-03-10 03:10 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("close", func(t *testing.T) {
TestRows_Close已经表明了测试Rows.Close,这里再描述就该是场景了,比如: 1) 生效, 2)多次调用等效 等

2023-03-10 03:27 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_多个sqlRows_部分sqlRows返回行数相同_顺序读取各个sqlRows",
我下面我记得写了一个呀

2023-03-10 03:29 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_多个sqlRows_每个sqlRows返回行数相同_交叉读取各个sqlRows",
请给出 “轮训”“顺序”“交叉”的实例, 假设有3个sqlRows,每个sqlRows返回2行数据.

2023-03-10 03:39 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_多个sqlRows_每个sqlRows返回行数相同_交叉读取各个sqlRows",
可以，顺序读定义明确；交叉要不要分为部分交叉和全交叉？为什么不要？

2023-03-10 03:40 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_多个sqlRows_每个sqlRows返回行数相同_交叉读取各个sqlRows",
我改改

2023-03-10 03:46 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("close", func(t *testing.T) {
你是说修改那个name吗？

2023-03-10 03:49 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("close", func(t *testing.T) {
在TestRows_Close下写两个子测试并恰当命名,一个验证Close生效了,一个验证多次调用等效

2023-03-10 03:59 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_多个sqlRows_每个sqlRows返回行数相同_交叉读取各个sqlRows",
那我再加一个部分交叉的例子：有一行一次性全部读完。两行的交叉着读

2023-03-10 06:47 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("close", func(t *testing.T) {
大佬这两个如果抽取成那种testcases的形态，我会觉得有些冗余，因为这两个不能抽取出共同点去assert。你觉得可以放在一起吗，或者有什么其他优雅的方法去写吗

2023-03-10 07:08 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("close", func(t *testing.T) {
就用t.Run的形式写子测试就行，运行测试时读的要通顺TestRows_Close/xxxx, TestRows_Close/YYYY

2023-03-11 11:18 UTC, longyue0521 requested changes

2023-03-11 11:18 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC,name ASC_每个sqlRows行数不同_全部交叉读取各个sqlRows",
每个slqRows返回行数都不同

2023-03-11 11:18 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC,name DESC_每个sqlRows行数相同_全部交叉读取各个sqlRows",
每个slqRows返回行数都相同

2023-03-11 11:18 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列name ASC,id DESC(排序列出现的顺序和sqlRows的顺序不同)_返回的行数全部相同_全部交叉读取各个sqlRows",
你把各个用例的name都抽取出来，放在一起比较一下，name的命名规则/模式要保持一致，请仔细校验后续全部name，将其改为统一命名形式，保证测试的可读性。

通过仔细阅读这些name看看你还缺哪些用例，比如：id DESC, name DESC

2023-03-11 11:18 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC,name ASC_其中有一个sqlRows的数据为空的在中间_部分sqlRows返回行数相同_全部交叉读取各个sqlRows",
`其中有一个sqlRows的数据为空的在中间` 去掉

2023-03-11 13:57 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列name ASC,id DESC(排序列出现的顺序和sqlRows的顺序不同)_返回的行数全部相同_全部交叉读取各个sqlRows",
名字可以取得比较简洁，然后如果觉得名字不够细节，那么在前面加上一个注释也可以。

2023-03-11 14:26 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_部分sqlRows返回行数相同_顺序读取各个sqlRows",
我觉得 longyue 的想法是说，在这个测试用例设计上，有几个因素会影响 Next 在不同的 sql.Rows 里面切换：
- 完全交叉、部分交叉和完全不交叉
- 行数，部分数量比较少的行会提前结束，那么其它 Rows 依旧能够正确被读取完毕。那么极端的情况就是大家行数都不同，行数都相同；再结合行数可以为0，那么可以是头几个为行数为0，后几个行数为0，中间几个行数为0

有一些你在这个测试用例里面可以不体现的，就是排序列是正序还是倒序，以及多少个排序列。这部分是你的 heap 实现来保证的，这边有一个简单的例子就差不多——主要是确保 Heap 和 Next 运作正常。

2023-03-12 00:43 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_部分sqlRows返回行数相同_顺序读取各个sqlRows",
1. 完全交叉，行数相同
2. 完全交叉，行数部分不同
3. 完全交叉，行数完全不同
4. 部分交叉，行数相同
5. 部分交叉,  行数部分不同
6. 部分交叉，行数完全不同
7. 顺序读，行数相同
8. 顺序读，行数部分不同
9. 顺序读，行数完全不同
// 这边就部分交叉读什么的了，上面已经讨论过了，以完全交叉读为例
10. 返回的行数为0，在前面
11. 返回的行数为0，在中间
12. 返回的行数为0，在后面

2023-03-12 00:43 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_部分sqlRows返回行数相同_顺序读取各个sqlRows",
@longyue0521 @flycash 这样搞你们觉得还行不

2023-03-12 00:45 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_部分sqlRows返回行数相同_顺序读取各个sqlRows",
13. 排序列返回的顺序和数据库里的字段顺序不一致

2023-03-12 03:21 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_部分sqlRows返回行数相同_顺序读取各个sqlRows",
> 有一些你在这个测试用例里面可以不体现的，就是排序列是正序还是倒序，以及多少个排序列。这部分是你的 heap 实现来保证的，这边有一个简单的例子就差不多——主要是确保 Heap 和 Next 运作正常。

我赞同 @flycash的建议，但这是有前提的——你抽取出去的heap有对应的测试覆盖来保证。现在的情况是抽取出的heap没有对应用的测试测试，所以这里只能用类似于”集成测试“或粒度更大的单元测试的概念来保证正确性。

>返回的行数为0，在前面
>返回的行数为0，在中间
>返回的行数为0，在后面
>返回的行数全部为0

这几种情况都可以通过精心设计测试数据，融入到 1～9 测试用例中，比如`返回的行数全部为0`就是`XXXX，行数相同`的一种特例。`中间/前面返回的行数为0`可以体现在`xxx,行数完全不同`或`xxx,行数部分不同`中。

2023-03-12 03:29 UTC, longyue0521 requested changes

2023-03-12 03:29 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "部分sqlRows返回的行数为0，在前面",
按照我上一个留言，将”返回行为0“出现的位置，融入到之前的测试用例中。再次检查name的命名，使其保持一致、可读性。

2023-03-12 03:29 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestRows_Close() {
设计测试用例，覆盖Close返回mulitierror的情况。

2023-03-12 03:54 UTC, longyue0521 commented
@juniaoshaonian @flycash 

当前实现缺少的测试：

1. 缺少Err方法的测试
2. 缺少Err方法与Next/Scan/Close方法各种交叉调用的测试
4. 缺少Close返回multierror的场景测试
5. 并发测试——merger.Rows各个方法在并发场景下的测试
6. 缺少边界情况的测试，即确认不同的方法调用顺序导致merger.Rows的状态迁移是否明确，例如：拿到merger.Rows
    - 直接Scan会发生什么？
    - 假设sqlRows返回行为都为0，调用Next后，Err()返回什么？ 
    - Close后再次调用Scan会发生什么？
    - 等等。
    
@juniaoshaonian 读源码或者实际测试一下sql.Rows在上面各种情况的表现，尽可能做到与sql.Rows语义一致。

2023-03-12 05:37 UTC, flycash commented
这边测试的话，拆成不同的方法，比如说 Err 一个方法， Err 和 Scan 交叉的再拆出来一个方法。这样我们的 test case 的名字就不至于非常长。这种组织方式，也更加容易理解。

另外有一个测试，就是 Err 不会 nil 之后再次尝试 Scan 会发生什么？或者说在 Scan 中间发现了 Err，继续 Scan 会怎么办。

2023-03-13 03:24 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列id ASC_部分sqlRows返回行数相同_顺序读取各个sqlRows",
我觉得可以的。这边我比较建议你把和排序本身相关的挪过去 heap 那边。然后这边集中测试不同行数，以及交叉情况的用例

2023-03-13 14:51 UTC, juniaoshaonian commented
关于并发测试应该怎么测，我的理解我们保证的是单个Next或者Scan，他们两和起来不是并发安全的，sql.rows里面的Next，Scan方法都加了读写锁。但是这个咋测单个Next和Scan是并发安全的，大佬们有没有想法聊聊呀。

2023-03-13 14:56 UTC, flycash commented
合并一下最新代码

2023-03-13 15:30 UTC, closed without merging