分库分表： merger排序实现
ecodeclub/eorm pull request #169
Opened 2023-03-13 15:57 UTC by juniaoshaonian

合并了一下代码

2023-03-14 10:46 UTC, longyue0521 requested changes

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "完全交叉读，sqlRows行数部分不同",
sqlRows行数部分不同 -> sqlRows返回行数部分不同

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "部分交叉读，sqlRows行数相同",
sqlRows返回行数完全相同

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "部分交叉读，sqlRows行数部分相同",
sqlRows返回行数部分相同

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "顺序读，sqlRows返回行数相同",
sqlRows返回行数完全相同

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列返回的顺序和数据库里的字段顺序不一致",
写这个测试用例的目的是什么？

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *MergerSuite) TestCompare() {
移动到heap_test.go中

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func (r *Rows) Columns() ([]string, error) {
这里要不要加锁？

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +func (r *Rows) Close() error {
这里要不要加锁？g1调用Next，g2调用Close

2023-03-14 10:46 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +	for i := 0; i < len(dest); i++ {
264行处要不要检查`r.lastErr != nil`?,如果要，写测试复现这个bug再添加产品代码；如果不要，说说为什么？

2023-03-14 10:47 UTC, longyue0521 requested changes

2023-03-14 10:47 UTC, longyue0521 commented on sharding_db.go
> +// nolint
这个文件你不应该修改吧，加这个是为什么？

2023-03-14 10:55 UTC, longyue0521 commented
@juniaoshaonian 学习一下git rebase 这样你应该就不用关闭之前的PR https://github.com/ecodeclub/eorm/pull/166

2023-03-14 11:06 UTC, juniaoshaonian commented on sharding_db.go
> +// nolint
这个他们还没做完，我不加这这个，golint检查会报错

2023-03-14 11:08 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func (r *Rows) Close() error {
不加，我close只会将状态从false变成true，多次调用也是等效的

2023-03-14 11:10 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列返回的顺序和数据库里的字段顺序不一致",
我之前返回列的顺序和数据库里的字段不一致，就出问题了。

2023-03-14 11:13 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func (r *Rows) Close() error {
如果加锁只能用不同的锁，因为我在next里面也调了这个方法，但我想到上面讲的我感觉加的意义不大

2023-03-14 11:18 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	for i := 0; i < len(dest); i++ {
不需要如果迭代过程中出现error的情况，我会调用close方法将状态修改。

2023-03-14 11:33 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +func (r *Rows) Close() error {
加

2023-03-14 11:40 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +			name: "排序列返回的顺序和数据库里的字段顺序不一致",
以用户定义sortColumns的顺序为准，我之前写的有点问题，没按用户在NewMerger指定的sortColumns的顺序。所以加了这个测试

2023-03-14 16:15 UTC, longyue0521 requested changes

2023-03-14 16:15 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	})
缺少Close生效测试用例, 先读到数据,再调用rows.Close(),无法再读——1)Close后Next返回false 2)Close后Scan返回Next中的迭代错误或者“已关闭”错误, 3) Close后调用Columns方法返回已关闭),以此证明生效

2023-03-14 16:20 UTC, longyue0521 requested changes

2023-03-15 00:24 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	})
我在close里面也加了锁，所以要在close之前把锁解了。就不好这么改了

2023-03-15 02:32 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +	})
```go
r.once.Do(....) // 去掉内部r.mu.Unlock()
r.mu.Lock()
defer r.mu.Unlock()
```
为什么不能这么改？

2023-03-15 02:42 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +	})
```go
r.mu.Lock()
r.once.Do(func() {
	     // ...
	     ok := r.nextRows(r.rowsList[i], i)
	     if !ok {
	         r.mu.Unlock()
                 _ = r.Close()
                 // 这里的return只能使执行流程从Done中匿名函数退出，在Next中还要向下执行的
		return
	     }
	   }
})
// 走到这里r.mu已经解锁了
if r.hp.Len() == 0 || r.lastErr != nil { // 并发安全？
                // 二次解锁？
		r.mu.Unlock()
		return false
}
```

2023-03-15 07:24 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger.go
> +	})
对哦，我把加锁的步骤改到下面。

2023-03-15 09:14 UTC, flycash commented on internal/merger/sortmerger/merger.go
> +	for i := 0; i < len(dest); i++ {
确实要先判断 lastErr，再判断 closed 的信号。这里我们倒是不需要检测 EOF 错误，我觉得。即任何错误在我们这里都是不做区分的，也不做容错，所以都要直接返回

2023-03-15 09:25 UTC, juniaoshaonian commented
大佬们关于Next遍历完自动调用close方法的问题，你们觉得现在要怎么处理

func (rs *Rows) nextLocked() (doClose, ok bool) {
	if rs.closed {
		return false, false
	}

	rs.dc.Lock()
	defer rs.dc.Unlock()
	if rs.lastcols == nil {
		rs.lastcols = make([]driver.Value, len(rs.rowsi.Columns()))
	}
	//当遍历到最后一行时会返回EOF这个错误
	rs.lasterr = rs.rowsi.Next(rs.lastcols)
	if rs.lasterr != nil {
        
		if rs.lasterr != io.EOF {
			return true, false
		}
		nextResultSet, ok := rs.rowsi.(driver.RowsNextResultSet)
		if !ok {
			return true, false
		}
        // 如果是EOF错误并且没有下一个结果集就会把他关闭 
		if !nextResultSet.HasNextResultSet() {
			doClose = true
		}
		return doClose, false
	}
	return false, true
}
// dbClose为true就会调用close方法

2023-03-15 09:37 UTC, juniaoshaonian commented
还有Columns方法，一个sql.Rows遍历完如果再调用Columns方法会直接报连接已关闭的错误，我的想法是如果遇到连接已关闭的错误就继续下一个sql.Rows。但是如果是其他错误应该怎么办，直接返回还是说继续遍历下一个。还是说遇到错误直接不管一直遍历下去直到最后一个，返回最后一个的错误？

2023-03-15 09:38 UTC, juniaoshaonian commented
@longyue0521 @flycash

2023-03-15 12:34 UTC, longyue0521 commented
> 大佬们关于Next遍历完自动调用close方法的问题，你们觉得现在要怎么处理
> 
> ```
> func(rs *Rows) nextLocked() (doClose, ok bool) {
> 	if rs.closed {
> 		return false, false
> 	}
> 	rs.dc.Lock()
> 	defer rs.dc.Unlock()
> 	if rs.lastcols == nil {
> 		rs.lastcols = make([]driver.Value, len(rs.rowsi.Columns()))
> 	}
> 	//当遍历到最后一行时会返回EOF这个错误
> 	rs.lasterr = rs.rowsi.Next(rs.lastcols)
> 	if rs.lasterr != nil {
>         
> 		if rs.lasterr != io.EOF {
> 			return true, false
> 		}
> 		nextResultSet, ok := rs.rowsi.(driver.RowsNextResultSet)
> 		if !ok {
> 			return true, false
> 		}
>         // 如果是EOF错误并且没有下一个结果集就会把他关闭 
> 		if !nextResultSet.HasNextResultSet() {
> 			doClose = true
> 		}
> 		return doClose, false
> 	}
> 	return false, true
> }
> // dbClose为true就会调用close方法 
> ```

按之前聊过的,尽可能与sql.Rows的各个方法语义保持一致.

在单结果集下,sortmerger.Rows.Next在非异常情况下返回false表明内部heap中没有预Scan的行了,而在预Scan之前都会先调用一下sql.Rows.Next如果其返回false也就是会自动关闭,所以现在来看sortmerger.Rows.Next可以说是做到了下面这个部分:

> 		nextResultSet, ok := rs.rowsi.(driver.RowsNextResultSet)
> 		if !ok {
> 			return true, false
> 		}

sortmerger.Rows.Next在异常情况下返回false即内部在迭代sql.Rows时或者预Scan时报错的情况下,也设置了r.lasterr并执行了r.Close可以说是做到了下面这部分:

if rs.lasterr != io.EOF {
> 			return true, false
> 		}

在多结果集的情况,sortmerger.Rows暂时不支持所以没有处理多结果集的情况.多结果集处理起来也有坑:假设从三个sqlRows取数据,每个sqlRows有2个结果集.sqlRows1的第一个结果集最先被取完,这时是直接取其下一个结果集的数据还是等待sqlRows2和3的第一个结果集都取完,然后调用三者的NextResultSet再一起从各自第二个结果集里取数据? 简单描述就是多个sqlRows的多个结果集之间数据能否交叉取?

2023-03-15 12:47 UTC, longyue0521 commented
> 还有Columns方法，一个sql.Rows遍历完如果再调用Columns方法会直接报连接已关闭的错误，我的想法是如果遇到连接已关闭的错误就继续下一个sql.Rows。但是如果是其他错误应该怎么办，直接返回还是说继续遍历下一个。还是说遇到错误直接不管一直遍历下去直到最后一个，返回最后一个的错误？

这么做确实可以,但也依赖于一个假设——所有sql.Rows的列都是相同的,之所以称之为假设,因为在NewSortMerger的时候并没有检查各个sqlRows的列是否相同,可以考虑把这个假设变为约束同时把你上面提到的`如果是其他错误应该怎么办`前置到NewSortMerger阶段,在检查各个sqlRows的列是否相同的同时在Rows内部缓存一份列集及其类型,这样就与底层sqlRows解耦了,可以根据sortmerger.Rows内部的状态来定义返回而不再依赖于底层sqlRows以及处理其error

2023-03-15 15:14 UTC, longyue0521 requested changes

2023-03-15 15:14 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +		}
添加一个row.Err的断言,证明迭代期间没有发生错误.

2023-03-15 15:14 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("Next迭代完", func(t *testing.T) {
添加一个对rows.Next和row.Err的断言,证明迭代已结束,且没法生任何错误

2023-03-15 15:24 UTC, longyue0521 commented
@juniaoshaonian 请保持PR的单一性,在这个PR中只修改sortmerger相关代码,把你bachmerger相关代码的修改revert回去,另外开PR处理.不要混在一起改.

2023-03-16 00:58 UTC, juniaoshaonian commented
> @juniaoshaonian 请保持PR的单一性,在这个PR中只修改sortmerger相关代码,把你bachmerger相关代码的修改revert回去,另外开PR处理.不要混在一起改.

我改了一下errror的名字，和加了err()方法，让他们不报错

2023-03-16 01:37 UTC, juniaoshaonian commented
> 

大佬你知道正常情况SortMerger中的传入的sql.Rows列表中的元素他的columns返回的元素顺序是一致的吗

2023-03-16 02:13 UTC, flycash commented on internal/merger/batchmerger/merger.go
> +func (m *MergerRows) Err() error {
这个不实现的话，直接用 panic，后面再开一个合并请求

2023-03-16 02:13 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +	err = rows.Close()
下面的这些测试用例应该就算了吧？用户在 Close 之后，就不能再使用其他方法了

2023-03-16 02:23 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	err = rows.Close()
我认为需要,因为Rows是并发安全的,我们没写并发测试,需要在各个方法内检测是否被关闭.

2023-03-16 02:25 UTC, longyue0521 commented
@flycash 

看一下 
1. https://github.com/ecodeclub/eorm/pull/169#issuecomment-1469924139
2. https://github.com/ecodeclub/eorm/pull/169#issuecomment-1469945680

2023-03-16 06:49 UTC, juniaoshaonian commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("Close之后，调用Scan", func(t *testing.T) {
没区别，我删了吧

2023-03-16 12:34 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +	err = rows.Close()
可以

2023-03-16 12:37 UTC, flycash commented
- 多结果集的问题：首先第一个是 longyue 提到的，我们难以确定是不是大家的第一个结果集都处理完了，再同时开启第二个结果集；第二点是我认为用户不应该使用多结果集，因为多结果集还涉及到两次查询列不一样，比如说 select a from; select b from; 甚至于 select 和 update 混用；第三则是，按照道理来说，sql.Rows 内部已经尝试了 next result set，我们自己就不处理了。可以说，多结果集情况下，我们依赖于 sql.Rows 本身的语义。那么也就是如果全部结果集都相等，那么排序就是全部结果集一起参与排序；
- 所有结果的列都是一样的：这个是非常强的假设，或者说是我们这个 merger 运作的基石。虽然理论上来说大家列不一样，但是排序列都一样的话我们也能处理，但是这个场景不对。在我们预期中，这个东西就应该是给相似的查询用的，也就是返回的列必须都一样。甚至于，我都认为这是一个连检测都不需要检测的假设，因为用户但凡用这个merger，他就应该知道如果列不一样或者排序列不一样会有什么奇怪的事情发生。毕竟这不是一个直面普通开发的东西，是一个给高级开发人员用的；

https://github.com/ecodeclub/eorm/pull/169#issuecomment-1469924139 这个地方是要加并发测试吗？@longyue0521?

2023-03-16 13:37 UTC, longyue0521 commented
> 第三则是，按照道理来说，sql.Rows 内部已经尝试了 next result set，我们自己就不处理了。可以说，多结果集情况下，我们依赖于 sql.Rows 本身的语义。那么也就是如果全部结果集都相等，那么排序就是全部结果集一起参与排序；

sql.Rows只是调用HasNextResultSet检测一下是否有下一个结果集并不会自动跳到下一结果集，需要用户显示调用sql.Rows.NextResultSet方法跳到下一个结果集。

> 所有结果的列都是一样的：这个是非常强的假设，或者说是我们这个 merger 运作的基石。虽然理论上来说大家列不一样，但>是排序列都一样的话我们也能处理，但是这个场景不对。在我们预期中，这个东西就应该是给相似的查询用的，也就是返回的>列必须都一样。甚至于，我都认为这是一个连检测都不需要检测的假设，因为用户但凡用这个merger，他就应该知道如果列不>一样或者排序列不一样会有什么奇怪的事情发生。毕竟这不是一个直面普通开发的东西，是一个给高级开发人员用的；

好的，在顶层抽象Merger接口加个注释怎么样，一方面介绍Merger的作用，另一方面提示一下：[]sql.Rows中每个sql.Rows**仅支持单个结果集**且每个sql.Rows中**列集必须完全相同**。

> 
> [#169 (comment)](https://github.com/ecodeclub/eorm/pull/169#issuecomment-1469924139) 这个地方是要加并发测试吗？@longyue0521?
 
不是，是为了回答这个问题 https://github.com/ecodeclub/eorm/pull/169#issuecomment-1469649466

我认为现在sortmerger.Rows.Next的语义符合sql.Rows.Next的语义

2023-03-16 13:39 UTC, flycash commented
> 好的，在顶层抽象Merger接口加个注释怎么样，一方面介绍Merger的作用，另一方面提示一下：[]sql.Rows中每个sql.Rows仅支持单个结果集且每个sql.Rows中列集必须完全相同。

OKKK

2023-03-16 13:53 UTC, longyue0521 requested changes

2023-03-16 13:53 UTC, longyue0521 commented on internal/merger/sortmerger/merger.go
> +// Merger  如果有 GroupBy 子句，那么该实现无法运作正常
这个注释细化一下，把为什么无法正常运作说一下，这样使用者踩坑后会省去debug的时间。

2023-03-16 13:53 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +	ms.T().Run("未调用Next，直接Scan", func(t *testing.T) {
把结果加上，“未调用Next，直接Scan，报错/返回错“

2023-03-16 13:56 UTC, longyue0521 commented
> > 好的，在顶层抽象Merger接口加个注释怎么样，一方面介绍Merger的作用，另一方面提示一下：[]sql.Rows中每个sql.Rows仅支持单个结果集且每个sql.Rows中列集必须完全相同。
> 
> OKKK

@juniaoshaonian 按上面的描述添加一下注释，再我把上面提到注释改了，这个PR就OK了

2023-03-16 14:04 UTC, longyue0521 commented
@juniaoshaonian 在最顶层Rows接口上也加一个注释：各方法用法及语义尽可能与sql.Rows

2023-03-16 14:35 UTC, flycash approved these changes

2023-03-16 14:35 UTC, merged