分库分表：batchMerger代码修改
ecodeclub/eorm pull request #172
Opened 2023-03-17 03:41 UTC by juniaoshaonian

- 添加Err的相关处理
- 修改相关的测试

2023-03-18 05:07 UTC, longyue0521 requested changes

2023-03-18 05:07 UTC, longyue0521 commented on internal/merger/batchmerger/merger_test.go
> +func (ms *MergerSuite) TestRows_NextErr() {
TestRows_NextAndErr

2023-03-18 05:07 UTC, longyue0521 commented on internal/merger/batchmerger/merger_test.go
> +func (ms *MergerSuite) TestRows_ScanErr() {
TestRows_ScanAndErr

2023-03-18 06:01 UTC, juniaoshaonian commented on internal/merger/batchmerger/merger.go
> +func (*Rows) nextRows(row *sql.Rows) (canNext bool, err error) {
这个我没用到r，我加上的话这边的deepsource检查会报错。要不我让这个方法不作为Rows的方法。你觉得这样咋样

2023-03-18 11:42 UTC, longyue0521 requested changes

2023-03-18 11:42 UTC, longyue0521 commented on internal/merger/batchmerger/merger.go
需要修复CI提示的错误，Format Go Code及changelog（更新修改日志） 点击后面的 Details根据提示做修复

2023-03-18 11:42 UTC, longyue0521 approved these changes

2023-03-18 11:58 UTC, juniaoshaonian commented
本次合并请求是对上次的批量查询的修改，就不加进changelog里面了

2023-03-22 02:51 UTC, flycash approved these changes

2023-03-22 02:51 UTC, flycash commented on internal/merger/batchmerger/merger.go
有时间可以顺手发一个合并请求修一下吗？

2023-03-22 02:52 UTC, merged