feature: 分库分表: 范围查询支持
ecodeclub/eorm pull request #181
Opened 2023-03-28 12:00 UTC by Stone-afk

2023-03-28 12:27 UTC, Stone-afk commented
单元测试正在补

2023-04-01 09:30 UTC, Stone-afk commented
<img width="747" alt="image" src="https://user-images.githubusercontent.com/73482944/229278068-52e70359-442b-4fbb-b7a9-45e02f0e0406.png">

2023-04-01 13:11 UTC, flycash commented
先挂起，等你的 Datasource 合并进去再说

2023-04-03 07:20 UTC, flycash commented on sharding_select.go
> +		return sharding.EmptyResult, errs.NewUnsupportedOperatorError(pre.op.Text)
随便加一个测试，比如说 Like 查询覆盖这里

2023-04-03 07:20 UTC, flycash commented on sharding_select.go
> +	fmt.Println("--------------")
这种 DEBUG 语句删掉

2023-04-03 07:20 UTC, flycash commented on sharding_select.go
> +		fmt.Println(q.SQL)
DEBUG 语句删掉

2023-04-03 07:20 UTC, flycash commented on sharding_select.go
> +	fmt.Println("--------------")
删掉

2023-04-03 07:26 UTC, flycash commented on sharding_select.go
> +	case opIn:
我现在回比较犹豫这个地方要怎么进一步优化。试想一下，如果用户准备实现一个自定义的分库分表算法，然后他怎么知道要考虑哪些操作符，哪些操作符他不需要考虑？

2023-04-03 07:28 UTC, flycash commented on sharding_select.go
> +	case opIn:
怎么把这种共性和个性告诉准备自定义算法的人。或者说，即便不考虑自定义算法，如果我们社区将来有一个新人进来了，他准备提供一个新的算法，怎么在不阅读这个地方代码的情况下，理解分库分表算法的运作机制。

这看起来比较难。

2023-04-07 14:22 UTC, Stone-afk commented on sharding_select.go
> +	case opIn:
这个估计得依赖于后期文档，如果没有确实很难

2023-04-08 12:34 UTC, flycash requested changes
补测试。你的异常分支应该也是测得到的。

2023-04-08 12:34 UTC, flycash commented on .CHANGELOG.md
> +<<<<<<< HEAD
你解决冲突这个地方忘记删了

2023-04-08 12:34 UTC, flycash commented on sharding_select.go
> +		q := query
403-404 没测试？

2023-04-08 12:35 UTC, flycash commented
一般来说，error 分支都是要覆盖到的，除非实在是没办法。覆盖 error 分支很重要的一个点是确保程序如预期返回 error 了，也就是把行为固化下来；一方面也是为了确切验证，error 不仅返回了，还是我们预期的那个 error。比如说之前我们就遇到过，虽然都返回了 error，但是 error 其实是另外一个 error，引起的线上故障。

2023-04-08 17:40 UTC, Stone-afk commented on sharding_select.go
> +		q := query
getMulti 测不了哇，你想想看是不是，构造不了多个库的查到不太的结果

2023-04-09 10:17 UTC, flycash reviewed
其它你总能测了吧

2023-04-09 10:17 UTC, flycash commented on sharding_select.go
> +		q := query
没懂你的意思。你是说之前我让你只支持 EQ 的那个假设吗？

2023-04-11 14:28 UTC, Stone-afk reviewed
mark

2023-04-12 06:02 UTC, flycash commented on .CHANGELOG.md
> +<<<<<<< HEAD
@Stone-afk 删了这个

2023-04-12 13:10 UTC, Stone-afk reviewed
mark

2023-04-13 11:03 UTC, Stone-afk reviewed
mark

2023-04-14 14:51 UTC, merged