分库分表：结果集处理——聚合函数（不含 Group By 子句)
ecodeclub/eorm pull request #187
Opened 2023-04-01 03:06 UTC by juniaoshaonian

2023-04-01 04:19 UTC, longyue0521 requested changes

2023-04-01 04:19 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/avg.go
为avg.go、count.go、max.go、min.go、sum.go添加测试用例

2023-04-01 04:19 UTC, longyue0521 commented on script/setup.sh
> +go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
这里为什么改为v1.52.2?

2023-04-01 05:20 UTC, longyue0521 requested changes

2023-04-01 05:20 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
1. 为什么AVG要接收两个类型参数S,C
2. 使用组合+委托——即用Count[T].Aggregate(columns)和Sum[T].Aggregate(columns)来实现AVG[T].Aggregate(columns)

2023-04-01 05:20 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/avg.go
> +func NewAVG[S AggregateElement, C AggregateElement](sumName string, countName string, name string) *AVG[S, C] {
countName和name什么区别? name指的是别名吗,如果是用alias

2023-04-01 05:20 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/max.go
> +	return ans[0], nil
1. columns为nil或空时, `return ans[0], nil` 会panic
2. 将ans的类型改为T重写比较逻辑.

2023-04-01 05:20 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/min.go
> +	return ans[0], nil
同上

2023-04-01 07:26 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/avg.go
这个我写在了NextAndScan里面了。

2023-04-01 07:26 UTC, juniaoshaonian commented on script/setup.sh
> +go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
因为使用latest我的ci检查过不了

2023-04-01 10:35 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
我需要count的Aggregate返回的类型和sum的Aggregate返回的类型，这两部分的值我们需要从哪获取

2023-04-01 10:36 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/avg.go
> +func NewAVG[S AggregateElement, C AggregateElement](sumName string, countName string, name string) *AVG[S, C] {
差不多，我改一下。这个name主要用于column()方法的返回值

2023-04-01 13:12 UTC, flycash commented on script/setup.sh
> +go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
那么检查一下所有的 CI 和脚本，都改成用固定版本

2023-04-01 13:32 UTC, flycash requested changes
明日再看看

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
既然只有 Sum 和 Count 两个，可以考虑定义两个字段。

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
把 merger_test 里面的测试拆一下，不同的聚合函数单独给一个方法，这样比较好维护

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +type AVG[S AggregateElement, C AggregateElement] struct {
我觉得这个地方不应该是泛型，因为我作为一个分库分表的调用者，实际上我也没办法在初始化的时候告诉你这里应该是 int 还是 float64。

不过暂时还没集成进去，所以用起来会是什么感觉也不清楚，暂时保持这样吧。

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +}
如果我的 Avg 是和别的混在一起计算的呢？ SELECT COUNT(id), AVG(age) 这种

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +}
就是这个 Index 是固定 0，和 1 让我觉得有点不太对

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/merger.go
> +	r.mu.Lock()
可以直接 defer Unlock 吗

2023-04-01 13:32 UTC, flycash commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getCols(row *sql.Rows) ([][]any, bool, error) {
从这里来看，我大概理解你的 AVG 里面 0 和 1 的问题了。其实你是相当于，针对每一个聚合函数，聚合函数告诉你这里，怎么排序这个数据？比如说 AVG 就要求你这里必须调整数据的位置，0是SUM，1 是 COUNT。

这很违背直觉。我更加倾向于，这里就是读出数据来，SELECT 是什么顺序就是什么顺序。然后聚合函数根据下标去取。

比如说 SELECT COUNT(ID), AVG(age) 转化为目标 SQL 之后是 SELECT  COUNT(ID), SUM(AGE), COUNT(ID) （分库分表不去重也可以），那么我在创建 Aggregator 的时候，我就这样创建：
```go
cnt := NewAggregator(ColInfo{name :"COUNT(ID)", Index 0}
avg := NewAggregator(ColInfo{name: "AVG(age)", SumIndex: 1, CountIndex:2}
```

好处就是比较清晰一点，毕竟永远操作的都是数据库返回来的那个顺序

2023-04-01 14:58 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
@flycash @juniaoshaonian 

我认为我们要建立的Aggregator抽象其语义是对某一聚合函数的多个聚合结果再次进行聚合,与数据库层面的对某一字段的多个值进行聚合(得到前面的聚合结果)是不一样概念——Aggregator抽象的输入其实是数据库已经聚合好的聚合结果,而数据库层面的聚合函数的输入通常情况下就是字段的值或表达式的值.

另外,数据库层面的聚合函数的返回值类型会随着输入值的类型的不同而发生变化.以mysql为例(其他数据库可能不同):

> The SUM() and AVG() functions return a DECIMAL value for exact-value arguments (integer or DECIMAL), and a DOUBLE value for approximate-value arguments (FLOAT or DOUBLE)

SUM()和AVG()返回值类型范围为{DECIMAL, DOUBLE} 具体为哪个与传入值的类型相关. 
一般情况下{DECIMAL, DOUBLE} 到Go中类型的映射由Go原生包和数据库driver包来完成,我们只需要从sql.Rows中取`SUM(col)`对应的值及类型信息直接返回就行了.但现在根据前面提到的Aggregator抽象语义,我们需要“拦截”这个值和类型信息用来再次进行聚合

所以我们要讨论一下

1. Aggregator抽象语义到底是什么?
2. AggregateElement到底是对什么的抽象/范型类型约束? 是否需要?
3. 以AVG()为例,拦截到的聚合结果类型可能为多种类型,如果被我们简单粗暴地统一转换为float64是否会有问题?
    - 用户用mysql的driver直接执行AVG()得到的聚合结果可能为多种类型,而经过我们分库分表中间件后只返回一种类型,与此同时我们对SUM的处理又不一样——不做任何转化,这会给用户造成困扰.
    - 我觉得我们只需要根据sql.Rows中对应的`AVG(col)`对应的值+类型来进行再聚合就好了不做任何中间转化,这样虽然麻烦一些但好处是可以适配多种driver. 
    - @juniaoshaonian `我需要count的Aggregate返回的类型和sum的Aggregate返回的类型，这两部分的值我们需要从哪获取` 我觉得要从sql.Row的ColumnType获取
 4. 我觉得这个功能与driver有些强相关,所以要用我们准备支持的driver集来写一些集成测试来验证一下——直接通过driver返回的聚合值及类型,与通过我们中间件后返回的聚合值及类型是否相同

2023-04-02 00:51 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
1. 我写的aggregator抽象语义是将几个库聚合函数计算的结果进行合并
2. 对aggregateElment是泛型类型约束。因为无论是Max min avg count 还是sum都应该是可被计算的。如果不对传参的类型进行约束。不好进行合并计算
3. 求avg是通过sum 和count相除求得的。所以我们并不能从原sql.Rows拿到avg的类型所以想用float64做个同意的处理
columnType我之前想在sortMerger的时候用的但是，但这个拿不到对应的类型会直接跳过

2023-04-02 00:55 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/merger.go
> +	r.mu.Lock()
这个应该不行，因为我需要在Next遇到错误的时候，调用Close的方法，close方法里面也会调用锁。如果直接使用defer的话就会造成close的时候因为拿不到锁而阻塞

2023-04-02 01:05 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getCols(row *sql.Rows) ([][]any, bool, error) {
我试试

2023-04-02 01:51 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
> * 我写的aggregator抽象语义是将几个库聚合函数计算的结果进行合并

我们的定义一致

> * 对aggregateElment是泛型类型约束。因为无论是Max min avg count 还是sum都应该是可被计算的。如果不对传参的类型进行约束。不好进行合并计算

你约束的其实是`Max min avg count sum`返回值的类型，正如我前面所说的不同的数据库这几个聚合函数的返回值的范围可能是不同的，这个应该由不同driver来决定。我们只读取

> 求avg是通过sum 和count相除求得的。所以我们并不能从原sql.Rows拿到avg的类型所以想用float64做个同意的处理

我们可以在改写SQL时候，添加一个`AVG(col)`，来获取其类型，而值还是通过sum和count来计算，并将这个`AVG(col)`
列隐藏在 merger.Rows内部只有我们自己知道。或者我们换一种方式通过通过 SELECT AVG(col) , Count(col)后计算得到sum(col):

Avg(col) = ( avg1(col) * count1(col) + avg2(col) * count2(col) ) / count1(col) + count2(col)

>   columnType我之前想在sortMerger的时候用的但是，但这个拿不到对应的类型会直接跳过

你指的拿不到，是通过sqlmock模拟的sql.Rows中拿不到，还是真实地连接用mysql driver连接mysql得到的sql.Rows中拿不到？ 两者可能存在差异，这也是我上面提到要有集成测试的原因。

2023-04-03 03:32 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
拿不到是指sqlmock的时候拿不到

2023-04-03 07:31 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
> Avg(col) = ( avg1(col) * count1(col) + avg2(col) * count2(col) ) / count1(col) + count2(col)

这种算法和 AVG(col) = SUM(col) + SUM(col)/COUNT(col) + COUNT(col) 比起来，会更加不准。就是你在数据库层面算出来的平均值是丢失了精度的平均值。所以要想最准确计算平均值，是不能用 AVG * COUNT 这种手段。

2023-04-03 07:31 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
aggregator 实际上就是算子。那么这个 merger 实现就可以算作是对 aggregator 自由组合的一个封装。

2023-04-03 07:35 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
目前来看，泛型在这里估计是不好用的，因为在初始化这个东西的时候，也不知道泛型的具体类型应该是什么。如果 sqlmock 里面拿不到我觉得很正常。真实的 driver 应该能拿到。可以试试。如果在真实的 driver 形态下能拿到，那么我们其它处理结果集的地方都可以改为使用 ColumnType

2023-04-03 07:39 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
关于精度的问题，其实我有一个很粗暴的想法。就是我们根本不考虑什么字段类型或者列的数据类型，而是直接采用粗暴的 decimal 来处理。而后当用户在调用 Scan 的时候，我们再转换过去对应的类型。
那么我来总结一下：
- 要么就用 ColumnType，根据这个东西的返回值来处理数字
- 要么就用 Decimal，牺牲一点性能

实际上，我认为不管是使用哪一种，最终计算出来的值可能都会有些精度之类的问题。尤其是 AVG 涉及到除法。

2023-04-04 12:30 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	}
暂时的话，因为本身 ColumnType 验证之后是可行的，那么就可以直接依赖于 ColumnType。在这种情况下，对应的 driver 实现者会保证数据类型是兼容的（Go类型和数据库类型兼容）。

引入中间表达的风险就是在于，数据库转中间表达到中间表达转Go类型，也会有一些类型方面的风险。

这里，有一个问题我觉得我们是不太需要考虑的。举例来说，比如说我们用 int64 收到了 Count 或者 Sum 之类的值，那么连续几个 COUNT 和 SUM 相加可能会溢出，即 int64 在这种情况下已经不能用了。

另外一个选择就是在计算这个值的时候，顺便检测一下相加之后是否会超出最大值或者最小值，以判断溢出的问题。

我目前的看法是……注释说明一下就可以了……

2023-04-06 13:49 UTC, longyue0521 requested changes

2023-04-06 14:06 UTC, longyue0521 requested changes

2023-04-06 14:06 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/max.go
> +		}
1. 抽取函数findExtremeValue(colsData [][]any, ExtremeValueFunc ) , func(xxx, yyy) bool
2. max/minAggregator委托给findExtremeValue(colsData [][]any, max/minExtremeValueFunc)

2023-04-07 05:17 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	colInfos []ColInfo
龙跃兄弟第二个是啥意思？

2023-04-07 05:51 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	colInfos []ColInfo
ColInfo可读性差点不那么直观，要么把Col写全，要么换一个全名

2023-04-07 11:52 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +	colInfos []ColInfo
在解释的时候要重点强调一下，我们并不能预期在不同的数据库上，精度会不会损失，自己损失的话会有多少的损失。这很大程度上跟数据库类型，数据库驱动实现都有关。多少算是一个免责声明了

2023-04-07 11:52 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/avg.go
> +var avgAggregateFuncMapping = map[[2]reflect.Kind]func([][]any) (any, error){
我想想这里有没有什么优化手段，实在是过于繁琐了=。=

2023-04-07 11:52 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/count.go
> +	var Count T
局部变量始终保持首字母小写

2023-04-07 11:52 UTC, flycash commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getAggregateInfo(rowsData [][]any) ([]any, error) {
可以多加一些注释解释每一个具体的步骤吗？这个逻辑有点绕

2023-04-07 11:52 UTC, flycash commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getAggregateInfo(rowsData [][]any) ([]any, error) {
我有一个疑问，比如说在你的测试里面：
```go
aggregator.NewAVG(aggregator.NewColInfo(4, "SUM(grade)"), aggregator.NewColInfo(5, "COUNT(grade)"), "AVG(grade)")
```
既然你在 aggregator 里面明确知道我的平均值所需的 SUM 在下标为 4 的列， COUNT 在下标为 5 的列。那么我在 AVG 计算的时候，我可以直接用这个下标。那么你在这里就不需要调整这个列的顺序，把它们放到第一第二了。
例如：
```go
func (a AVG) Aggregate(data [][]any) any {
     for _, row := range data {
         sum += row(a.sum.Index)
         count += row(a.count.Index)
     }
}
```
这个时候是不是可以将 Avg 设计为：
```go
type Avg struct {
   sum ColInfo
   count ColInfo
}
```
并且，应该也用不上 ColumnInfo 这个方法了。

2023-04-07 13:51 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/aggregator/max.go
> +		}
这个龙跃老哥不是很明白

2023-04-07 15:21 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/max.go
> +		}
max/minAggregator中只有 `if maxData < data {` 这里是不同的，那么可以抽取一个函数`func(maxData, data) bool { maxData < data }` 作为参数传入进去即`if f(maxData, data) {`从而复用剩下的代码。

2023-04-08 04:37 UTC, flycash commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getAggregateInfo(rowsData [][]any) ([]any, error) {
你这个你是解决了？我的问题貌似你还是没有回答，就是在我已经知道事实上它在返回数据的具体位置了，为啥我在这里还需要提取出来？

2023-04-08 05:08 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getAggregateInfo(rowsData [][]any) ([]any, error) {
等等我还没提交

2023-04-08 05:10 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/merger.go
> +func (r *Rows) getAggregateInfo(rowsData [][]any) ([]any, error) {
我改了

2023-04-09 10:12 UTC, flycash requested changes
我注意到一个问题，在除了 Avg 以外的所有的聚合函数都要求传入一个 alias，我看上去有点多余。比如说在 ColInfo 里面已经有了一个 name，那么在我的设想里面，这个 name 代表的就是我们的列名，即是数据库返回的列名，也是我们在 rows.Columns 里面使用的列名。

那么：
```sql
SELECT SUM(age) FROM
```
ColInfo.name 应该是 SUM(age)
而：
```sql
SELECT SUM(age) as sum_age FROM
```
这个 ColInfo.Name 就是 sum_age。

在结果集处理层面上，应该没有 alias 这个概念的。

2023-04-09 10:13 UTC, flycash commented on internal/merger/aggregatemerger/aggregator/max.go
> +		}
其实所有的，除了avg 都是可以抽取出来的。不过我后面再创建一个 issue 来跟进这个问题。目前这种简单的复制粘贴也可以接受，毕竟代码不是很复杂。

2023-04-10 02:42 UTC, longyue0521 requested changes

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/count.go
> +	countFunc, ok := countAggregateFuncMapping[kind]
1. 29-35行，抽取方法 countFunc, err := findCountFunc(cols[0])

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/max.go
> +	maxFunc, ok := maxFuncMapping[kind]
maxFunc, err := findMaxFunc(cols[0])

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/min.go
> +	}
minFunc , err := findMinFunc(cols[0])

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/max.go
> +		if extremeValueFunc(ans, data) {
改为 isExtremeValue

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/max.go
> +func maxValue[T AggregateElement](maxData T, data T) bool {
isMaxValue

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/min.go
> +func minValue[T AggregateElement](minData T, data T) bool {
isMinValue

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/sum.go
> +	}
sumFunc, err := findSumFunc(cols[0])

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/type.go
> +func NewColInfo(index int, name string) ColumnInfo {
NewColumnInfo

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/aggregator/sum.go
> +}
这个sumName不是可以从sumColumnInfo中取吗？为什么还要单独声明一个字段？

如果允许用户用其他的列名，应该作为参数传入NewSum中。将NewCount/Max/Min一并修改

2023-04-10 02:42 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger.go
> +	cols        []string
cols => columnNames

2023-04-10 07:06 UTC, flycash requested changes

2023-04-10 07:06 UTC, flycash commented on internal/merger/aggregatemerger/merger.go
> +	// hasClosed和hasOpen是为了当出现有RowsList中有一个或多个sql.Rows出现返回行数为空的时候报错（全部为空不会报错）。
我认为这里可以稍微简化一下这个标记位。
按照这个不支持 GROUP BY 的设计，用户传入的 rows 应该只有一行。所以实际上在 Next 方法里面可以用 once 来（或者原子操作标记位）表达用户是否已经取过数据了。在取过之后调用 Next 就直接返回 false。
那么相应的这里就可以简化为固定取走那一行的逻辑。
我觉得这样要比两个标记位 hasClosed 和 hasOpen 要更加清晰。
在 Merger 加上注释强调一下这个假设：该实现不支持 GROUP BY，并且聚合函数查询应该只返回一行数据。

2023-04-10 15:05 UTC, flycash requested changes

2023-04-11 02:12 UTC, longyue0521 requested changes

2023-04-11 02:12 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger.go
> +	r.hasNext = true
hasNext是用来做什么的？hasNext = true一般用来表示还有数据，可以继续，这里逻辑不对，也不需要hasNext

2023-04-11 13:12 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/merger.go
> +	r.hasNext = true
hasNext表示已经遍历过一次，只要遍历一次以后这个参数就为true。

2023-04-11 13:31 UTC, juniaoshaonian commented on internal/merger/aggregatemerger/merger.go
> +	r.hasNext = true
由于这个是不支持groupby的实现所以只会有一行数据。

2023-04-12 06:02 UTC, flycash commented
@juniaoshaonian deepsource 有一个小问题，你修复一下。
@longyue0521 确认没有问题之后你就可以合并了。

2023-04-12 06:02 UTC, flycash approved these changes

2023-04-12 08:32 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger.go
> +	r.hasNext = true
hasNext有些歧义，换个名字吧，nextHasCalled？nextCalled？

2023-04-12 08:33 UTC, longyue0521 commented
> 确认没有问题之后你就可以合并了。

OK

2023-04-12 10:09 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger_test.go
> +			name: "avg,sum,avg,min,min,max,count",
1. 重命名
2. max，count只出现一次，与上方注释不符

2023-04-12 10:10 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger_test.go
> +			name: "单个count",
COUNT(id)

2023-04-12 10:11 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger_test.go
> +			name: "AVG",
AVG(grade)

2023-04-12 10:27 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger_test.go
> +	wantCols := []string{"AVG(grade)"}
这里只测到了单个聚合函数，可以直接写一个“以grade为列的包含全部聚合计算函数含一定重复”的测试用例。

2023-04-12 10:50 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger.go
> +		columns:     m.colNames,
这里需要注释说明一下，聚合函数AVG传递到各个sql.Rows时会被转化为SUM和COUNT，这是一个对外不可见的转化。所以merger.Rows的列名及顺序是由上方aggregator出现的顺序及ColumnName()的返回值决定的而不是sql.Rows。

看看你能不能读懂，也可以自己再润色一下

2023-04-13 02:00 UTC, longyue0521 approved these changes

2023-04-13 02:07 UTC, longyue0521 requested changes

2023-04-13 02:07 UTC, longyue0521 commented on internal/merger/aggregatemerger/merger.go
> +	r.hasNext = true
hasNext有歧义，换个名字吧，nextHasCalled？nextCalled？

2023-04-13 12:24 UTC, Stone-afk reviewed
mark

2023-04-13 14:42 UTC, longyue0521 commented
@juniaoshaonian golangci-lint 问题修复一下

2023-04-13 14:47 UTC, juniaoshaonian commented
> @juniaoshaonian golangci-lint 问题修复一下

奇怪了我就改了个变量名呀，昨天还可以的

2023-04-14 15:46 UTC, longyue0521 approved these changes

2023-04-14 16:08 UTC, merged