修复单条查询时连接泄露问题
ecodeclub/eorm pull request #188
Opened 2023-04-02 12:28 UTC by hookokoko

在ecrom中是用eorm获取单条数据时，在task续约的时候会产生大量单结果查询，当超过150个select之后出现：

```
&mysql.MySQLError{Number:0x410, Message:"Too many connections"}
```

这种就是连接泄露了。看了下源码，只要在执行完for rows.Next() 遍历之后，这个连接就会被关闭，这里是Next源码：

```
func (rs *Rows) Next() bool {
	var doClose, ok bool
	withLock(rs.closemu.RLocker(), func() {
        // 这里如果读到最后一个数据，doClose为true，
        // 此时才会关闭，如果for Next()时数据没有遍历完就中断了，
        // 则就不会执行，那么这个连接就泄露了。
		doClose, ok = rs.nextLocked()
	})
	if doClose {
		rs.Close()
	}
	return ok
}
```

所以，改进就是在执行完
rows, err := sess.queryContext(ctx, qc.q.SQL, qc.q.Args...) 
之后调用下rows.Close()

2023-04-03 07:00 UTC, flycash commented on core.go
> +	defer rows.Close()
defer func() { _ = rows.Close()}

这样 CI 估计不会报错。
感谢=。=所以我说要用一个项目来验证。

2023-04-03 07:02 UTC, flycash requested changes
在 GetMulti 那里也显式地顺手关一下，检查一下

2023-04-03 07:38 UTC, hookokoko commented on core.go
> +	defer rows.Close()
不客气，大明赶紧摇点人来搞ecron~

2023-04-04 12:33 UTC, flycash commented on core.go
> +	}()
你放到检测 error 之后，这样就不用检测 rows 了。然后在 changelog 里面加一条

2023-04-04 13:29 UTC, flycash commented on core.go
> +
=。=我是说，在初始化 rows, err := 然后你紧接着判断 if err != nil 。在这个地方的后面

2023-04-04 13:29 UTC, flycash commented on core.go
> +
if !rows.Next() { 之前，defer 住

2023-04-07 11:23 UTC, merged