feature: 分库分表: NOT 支持
ecodeclub/eorm pull request #192
Opened 2023-04-16 07:27 UTC by Stone-afk

NOT 支持，部分集成测试待补充

2023-04-16 10:31 UTC, flycash requested changes
你的单测也没怎么覆盖啊！

2023-04-16 10:31 UTC, flycash commented on sharding_select.go
> +	case opAnd, opOr:
这边就不对了。在逻辑运算里面，(a =1 ) & (b=2) 取反是 (a != 1) || (b !=2)。也就是 AND 和 OR 是要换一下的。对于 OR 取反也是类似的

2023-04-16 11:04 UTC, Stone-afk commented on sharding_select.go
> +	case opAnd, opOr:
奥，搞错了

2023-04-16 11:05 UTC, Stone-afk commented on sharding_select.go
> +	case opAnd, opOr:
单测我看不出哪些地方没覆盖，之前的流水线 codecov/patch 点进去就可以看哪些没覆盖，现在点进去看不见了

2023-04-18 03:12 UTC, flycash commented on sharding_select.go
> +	case opAnd, opOr:
在 File changed 里面能够看到。等 CI 跑完它就会上去标记

2023-04-19 08:07 UTC, flycash commented on sharding_select.go
> +			return EmptyPredicate, err
把 EmptyPredicate 改成私有的吧。外面的人应该用不上这个东西

2023-04-19 08:09 UTC, flycash commented on sharding_select.go
> +	case opOr:
在类型 op 里面加一个字段，就是放对应的相反的操作符。那么大部分分支都是直接用相反的操作符。只有几个比较特殊的分支需要在这里额外处理，这样就能够极大的简化代码。
类似于：
```go
case opEQ, case opLT...(还有一堆):
   return Predicate{left left, op: o.negativeOp, right: right}
default:
   return nil, err
```
同时依旧保留default 分支防止我们出错。

2023-04-19 08:19 UTC, flycash commented on sharding_select_test.go
> +			name: "where not (gt eq and lt eq)",
加一个 where not ( eq and eq) 的测试用例。

2023-04-19 08:21 UTC, flycash commented on sharding_select_test.go
> +			name: "where not (gt eq and lt eq)",
分成两种情况，一个是 eq and eq 都是分库分表键；另外一个情况是只有一边是分库分表键

2023-04-19 08:25 UTC, flycash commented on sharding_select.go
> +		return s.mergeNotIN(results), nil
我觉得这个可以直接交给各个算法的实现者去处理，因为在这里处理不是很高效。比如说哈希和范围分库分表，在 NOT IN 的情况下，都是广播。我想着，只有非常罕见的按照枚举来分库分表的，比如说分库分表键只有 cn, us 两个值的，在 NOT IN 的时候可能不需要广播。

2023-04-19 08:26 UTC, flycash commented on internal/integration/sharding_select_test.go
> +			name: "where not lt",
任何一个单一操作符都要覆盖掉。

2023-04-22 03:31 UTC, flycash approved these changes

2023-04-22 03:31 UTC, merged