分库分表： 排序merger的nullable数据的支持
ecodeclub/eorm pull request #195
Opened 2023-04-24 15:42 UTC by juniaoshaonian

在sortmerger中支持nullable类型，大佬们看看这样搞可以不

2023-04-26 12:22 UTC, flycash commented on internal/merger/internal/errs/error.go
> +	ErrMergerNullAble                    = errors.New("merger: 接收数据的类型需要为sql.NullXXX")
Nullable

2023-04-26 12:22 UTC, flycash commented on internal/merger/sortmerger/heap.go
> +func compareNullable(ii any, jj any, order Order) int {
在这里加几句注释，说明排序的逻辑。因为后面的代码里面充斥着 if else 还是蛮难理解的。

然后各种异常场景都要覆盖掉。

此外我有一个问题，在正常的用法里面，我们这边不会传进来一个 *sql.NullXXX 这种指针吗?

2023-04-26 12:22 UTC, flycash commented on internal/merger/sortmerger/heap.go
> +func compareNullable(ii any, jj any, order Order) int {
如果我们用起来不可能是指针，那么就在注释里面也说明一下这点

2023-04-26 12:22 UTC, flycash commented on internal/merger/sortmerger/heap.go
> +func compareNullable(ii any, jj any, order Order) int {
其实我觉得，能不能用 driver.Valuer 来优化这个代码？因为 sql.NullXXX 都实现了这个接口。那么就可以直接断言是 driver.Valuer。然后调用 Value() 方法，再执行判断。最后只需要针对 Value 返回的值来做一个 switch 就可以了

2023-04-26 13:13 UTC, juniaoshaonian commented on internal/merger/sortmerger/heap.go
> +func compareNullable(ii any, jj any, order Order) int {
> 为后面的代码里面充斥着 if else 还是蛮难理解的。
> 
> 然后各种异常场景都要覆盖掉。
> 
> 此外我有一个问题，在正常的用法里面，我

应该不会我们从sql.rows里取数据的时候已经进行了取指针的操作

2023-04-26 13:16 UTC, juniaoshaonian commented on internal/merger/sortmerger/heap.go
> +func compareNullable(ii any, jj any, order Order) int {
> 其实我觉得，能不能用 driver.Valuer 来优化这个代码？因为 sql.NullXXX 都实现了这个接口。那么就可以直接断言是 driver.Valuer。然后调用 Value() 方法，再执行判断。最后只需要针对 Value 返回的值来做一个 switch 就可以了

可以我试试

2023-04-27 14:58 UTC, flycash commented on internal/merger/sortmerger/merger_test.go
> +func (ms *NullAbleMergerSuite) TestRows_NullAble() {
_Nullable

2023-04-27 14:58 UTC, flycash commented on internal/merger/utils/convert_Assign.go
> +func ConvertNullable(dest, src any) error {
在 default 分支里面返回 error。因为从你的代码里看，如果是 struct 的话，是不是只有 sql.NullXXX 这一种情况？或者说，我希望这个方法只用于 sql.NullXXX 的转换。但是实际上我觉得这种假设有点不靠谱，比如说如果我原本代码是使用 sql.NullInt32 来接收数据的，数据库类型是 bigint。按照道理来说，原本我的代码都运作得很好，除非溢出。

但是在我们的逻辑里面，因为在排序之前我们已经预先转到了 sql.NullInt64，所以这边再次尝试用 sql.NullInt32 读取就会失败。

我现在有这么一个想法，虽然对性能影响可能会很大。

首先，在merger 读取的时候，统一读取到 []bytes，作为原始数据。

而后在要排序的时候，将 []byte 转过去 sql.ScanType。但是 []byte 的原始数据会保留。

紧接着在用户真正要读取的时候，再一次从 []byte 里面转过去用户的目标类型。

我认为这样以 []byte 为准，每次转换都是从 []byte 转过去，就不会有什么类型转换的问题。

2023-04-27 14:58 UTC, flycash commented on internal/merger/utils/convert_Assign.go
> +func ConvertNullable(dest, src any) error {
我想要解决的核心问题就是，如果要是 sql.ScanType 给了我们 sql.NullXXX，而我作为一个实际用户，我想要用基本类型，或者 []byte, string 来接收数据，按照道理来说应该是没问题的。

你有没有别的解决思路？

2023-04-28 03:13 UTC, longyue0521 requested changes

2023-04-28 03:13 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +		wantVal     []NullAble
Nullable

2023-04-28 03:13 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +				db2InSertSql := []string{
InSert -> Insert

2023-04-28 04:19 UTC, longyue0521 commented on internal/merger/utils/convert_Assign.go
> +func ConvertNullable(dest, src any) error {
> 我想要解决的核心问题就是，如果要是 sql.ScanType 给了我们 sql.NullXXX，而我作为一个实际用户，我想要用基本类型，或者 []byte, string 来接收数据，按照道理来说应该是没问题的。

- 实际用户指的是eorm项目内其他用户,还是eorm项目外的最终用户.
- **我想要用基本类型，或者 []byte, string 来接收数据**,目的是给项目内其他用户提供方便,还是为项目外的最终用户提供增强功能?

在不使用eorm的情况下:
```
end user -> database/sql+driver
```
最终用户需要根据sql.Rows.ColumnTypes()中的多个ScanType来确定sql.Rows.Scan()时传入的各个数据类型. 如果sql.ColumnType.ScanType()返回sql.NullXXX那么,用户就应该用sql.NullXXX传入sql.Rows.Scan()来接收数据再自行转化为基本类型、[]byte,string等.

在使用eorm的情况下:
```
end user -> eorm + database/sql+driver
```
最终用户的使用习惯是否应该保持一致?
- 如果一致,那么eorm的merger.Rows要提供ColumnTypes方法与sql.Rows对齐.
  - 好处,最终用户使用习惯一致,实现简单不用考虑各个driver的兼容问题.
  - 排查问题也简单,是driver还是eorm的问题,只要去掉erom,再试一次通过比较前后两次行为是否一致就能知道.
- 如果不一致,相当于我们增强了功能,即最终用户既可以穿入sql.NullInt64,又可以传入int64, []byte等到eorm.Rows.Scan来接收数据.
  -  好处,方便最终用户使用
  - 但是实现时需要考虑各个driver,及同一个driver不同版本之前的差异,因为有的driver可能ScanType返回空接口,或者在不同的版本间返回了不同的类型.
 
是不是可以先将merger.Rows与sql.Rows对齐,使两者外在表现一致——即ScanType返回什么,Scan时就要穿入什么.再对merger.Rows进行封装增强——Scan时可传入的类型范围扩大.

2023-04-28 10:28 UTC, juniaoshaonian commented on internal/merger/utils/convert_Assign.go
> +func ConvertNullable(dest, src any) error {
我觉得搞成和sql.Rows一致就行，scan的话可以这样。如果用户使用不同类型的也可以处理,比如使用scanType解析成nullint64，用户可以使用nullint32 nullint64接受都行
![image](https://user-images.githubusercontent.com/73632785/235123077-c5526203-03a0-478e-aa81-37051d704251.png)

2023-04-30 13:22 UTC, flycash requested changes

2023-04-30 13:22 UTC, flycash commented on internal/merger/utils/convert_Assign.go
> +func ConvertAssign(dest, src any) error {
我觉得这里还是不太对。如果我的 src 是一个 sql.NullXXX 的话，而我的 Dst 是一个基本类型，那么你这里进去就会失败。但是没道理我这里应该失败。比如说我用 dest int32 去接收 src sql.NullInt32。

所以我觉得这个地方是不是直接改成这样就可以了：
```go
func ConvertAssign(dest, src any) error {
    srcVal, ok := src.(driver.Valuer)
    if ok {
       src, ok = srcVal.Value()
       if !ok {
             return // nil 的话这里应该不需要继续往下执行了
       }
    }
    return convertAssign(dest, src)
}
```
这样就规避了大多数的问题，但是依旧存在类型转换不了，以及 NULL 处理不正确的隐患。但是做到这个地步我觉得只能期待将来遇到问题之后再继续修补了。

如果这样的话，那么 ScannerAndValuer 也用不上了。

2023-04-30 13:22 UTC, flycash commented on internal/merger/utils/convert_Assign_test.go
> +func TestConvertNullable(t *testing.T) {
这里要增加 src 是 sql.NullXXX 但是 dest 并不是 sql.NullXX 的测试用例。

我倒是认为不必为 sql.NullXXX 和其它类型要进行笛卡尔积来组织测试用例——有点没有必要，因为本身什么类型能转换什么类型不能转换，sql.NullXXX 和 convertAndAssign 已经确保了。只需要确保 sql.NullXXX 转其它类型，跑到了 convertAndAssign 就可以了。

2023-05-02 15:07 UTC, flycash commented on internal/merger/utils/convert_Assign.go
> +	var err error
最后一点，将这个 err error 放进去 if ok 内部。然后再将文件名改名为 convert_assign.go 和 convert_assign_test.go

2023-05-02 15:14 UTC, flycash commented on internal/merger/utils/convert_Assign.go
> +	var err error
忽略，我先做一个小实验

2023-05-03 05:46 UTC, flycash commented
我已经验证过了，如果用户直接使用基本类型去接收 NULL，会出现 error。但是如果用户用基本类型的指针去接收 NULL，那么能够正常处理。

@longyue0521 的说法应该算是正确的，也就是我们倾向于认为用户应该使用 sql.NullXXX 类型或者自己实现类似的类型去处理 NULL 列。可惜的是 sql.NullXXX 出现得比较晚，所以目前 GO 这边的传统是用指针。

这也是很无奈的事情。

最后一点，将这个 err error 放进去 if ok 内部。然后再将文件名改名为 convert_assign.go 和 convert_assign_test.go

2023-05-03 05:46 UTC, flycash commented
#198

2023-05-03 05:48 UTC, flycash commented
把 deepsource 修一下，把 convertAssign 改名叫做 sqlConvertAssign。这个 deepsource 有点蠢。

2023-05-05 12:15 UTC, flycash commented
@longyue0521 可以再看看，没问题就直接合并了。

2023-05-06 09:41 UTC, longyue0521 commented
> @longyue0521 可以再看看，没问题就直接合并了。

好的

2023-05-06 10:22 UTC, longyue0521 requested changes

2023-05-06 10:22 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +			assert.Equal(t, tc.wantVal, res)
tc.afterFunc并没有调用

2023-05-06 10:22 UTC, longyue0521 commented on internal/merger/utils/convert_assign_test.go
> +		},
补充sql.NullXXX的Valid为false的情况

2023-05-06 10:22 UTC, longyue0521 commented on internal/merger/sortmerger/merger_test.go
> +func (ms *NullAbleMergerSuite) TearDownTest() {
TearDownTest是每个测试执行结束后执行的,所有测试结束后是TearDownSuite

2023-05-07 13:23 UTC, longyue0521 requested changes

2023-05-07 13:23 UTC, longyue0521 commented on internal/merger/utils/convert_assign_test.go
> +				require.NotNil(t, err)
require.Error(t, err)

2023-05-08 01:57 UTC, longyue0521 approved these changes

2023-05-08 02:03 UTC, merged